# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v15.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(744, 481)
        MainWindow.setMinimumSize(QtCore.QSize(744, 481))
        MainWindow.setMaximumSize(QtCore.QSize(744, 481))
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 721, 461))
        self.tabWidget.setMinimumSize(QtCore.QSize(721, 461))
        self.tabWidget.setMaximumSize(QtCore.QSize(721, 461))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("B Koodak"))
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        # self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.mainPage = QtGui.QWidget()
        self.mainPage.setObjectName(_fromUtf8("mainPage"))
        self.label = QtGui.QLabel(self.mainPage)
        self.label.setGeometry(QtCore.QRect(580, 30, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("B Koodak"))
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.mainPage)
        self.label_2.setGeometry(QtCore.QRect(600, 80, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("B Koodak"))
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.mainPage)
        self.label_3.setGeometry(QtCore.QRect(570, 130, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("B Koodak"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.LNEDTusername = QtGui.QLineEdit(self.mainPage)
        self.LNEDTusername.setGeometry(QtCore.QRect(450, 30, 110, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        self.LNEDTusername.setFont(font)
        self.LNEDTusername.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.LNEDTusername.setFrame(True)
        self.LNEDTusername.setEchoMode(QtGui.QLineEdit.Normal)
        self.LNEDTusername.setObjectName(_fromUtf8("LNEDTusername"))
        self.LNEDTpassword = QtGui.QLineEdit(self.mainPage)
        self.LNEDTpassword.setGeometry(QtCore.QRect(450, 80, 110, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(8)
        self.LNEDTpassword.setFont(font)
        self.LNEDTpassword.setEchoMode(QtGui.QLineEdit.Password)
        self.LNEDTpassword.setObjectName(_fromUtf8("LNEDTpassword"))
        self.CMBXlists = QtGui.QComboBox(self.mainPage)
        self.CMBXlists.setGeometry(QtCore.QRect(450, 130, 110, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.CMBXlists.setFont(font)
        self.CMBXlists.setObjectName(_fromUtf8("CMBXlists"))
        self.BTNreserv = QtGui.QPushButton(self.mainPage)
        self.BTNreserv.setGeometry(QtCore.QRect(450, 200, 75, 23))
        self.BTNreserv.setObjectName(_fromUtf8("BTNreserv"))
        self.QPTXTEDTlogs = QtGui.QPlainTextEdit(self.mainPage)
        self.QPTXTEDTlogs.setGeometry(QtCore.QRect(10, 10, 391, 360))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("B Koodak"))
        font.setBold(True)
        font.setWeight(75)
        self.QPTXTEDTlogs.setFont(font)
        self.QPTXTEDTlogs.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.QPTXTEDTlogs.setAutoFillBackground(False)
        self.QPTXTEDTlogs.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.QPTXTEDTlogs.setDocumentTitle(_fromUtf8(""))
        self.QPTXTEDTlogs.setReadOnly(True)
        self.QPTXTEDTlogs.setPlainText(_fromUtf8(""))
        self.QPTXTEDTlogs.setObjectName(_fromUtf8("QPTXTEDTlogs"))
        self.CHKBXthis = QtGui.QCheckBox(self.mainPage)
        self.CHKBXthis.setGeometry(QtCore.QRect(549, 180, 101, 31))
        self.CHKBXthis.setObjectName(_fromUtf8("CHKBXthis"))
        self.CHKBXnext = QtGui.QCheckBox(self.mainPage)
        self.CHKBXnext.setGeometry(QtCore.QRect(550, 210, 101, 31))
        self.CHKBXnext.setTristate(False)
        self.CHKBXnext.setObjectName(_fromUtf8("CHKBXnext"))
        self.CHKBXshowPassword = QtGui.QCheckBox(self.mainPage)
        self.CHKBXshowPassword.setGeometry(QtCore.QRect(420, 80, 20, 20))
        self.CHKBXshowPassword.setText(_fromUtf8(""))
        self.CHKBXshowPassword.setObjectName(_fromUtf8("CHKBXshowPassword"))
        self.tabWidget.addTab(self.mainPage, _fromUtf8(""))
        self.createNewList = QtGui.QWidget()
        self.createNewList.setObjectName(_fromUtf8("createNewList"))
        self.TABnewList = QtGui.QTabWidget(self.createNewList)
        self.TABnewList.setEnabled(True)
        self.TABnewList.setGeometry(QtCore.QRect(40, 40, 631, 371))
        self.TABnewList.setTabPosition(QtGui.QTabWidget.West)
        self.TABnewList.setTabShape(QtGui.QTabWidget.Triangular)
        self.TABnewList.setElideMode(QtCore.Qt.ElideNone)
        self.TABnewList.setDocumentMode(False)
        self.TABnewList.setObjectName(_fromUtf8("TABnewList"))
        self.restaurant = QtGui.QWidget()
        self.restaurant.setObjectName(_fromUtf8("restaurant"))
        self.frame = QtGui.QFrame(self.restaurant)
        self.frame.setGeometry(QtCore.QRect(10, 20, 581, 321))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(516, 50, 41, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.CMBbreak0 = QtGui.QComboBox(self.frame)
        self.CMBbreak0.setGeometry(QtCore.QRect(360, 50, 151, 22))
        self.CMBbreak0.setObjectName(_fromUtf8("CMBbreak0"))
        self.CMBbreak0.addItem(_fromUtf8(""))
        self.CMBbreak0.addItem(_fromUtf8(""))
        self.CMBbreak0.addItem(_fromUtf8(""))
        self.CMBbreak0.addItem(_fromUtf8(""))
        self.CMBbreak0.addItem(_fromUtf8(""))
        self.CMBbreak0.addItem(_fromUtf8(""))
        self.CMBbreak0.addItem(_fromUtf8(""))
        self.CMBbreak0.addItem(_fromUtf8(""))
        self.CMBbreak0.addItem(_fromUtf8(""))
        self.line = QtGui.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(7, 30, 561, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(510, 0, 20, 311))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(520, 90, 41, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(410, 10, 41, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(240, 10, 51, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(100, 10, 21, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(520, 130, 41, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(520, 170, 41, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(520, 210, 41, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(520, 250, 41, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(520, 290, 41, 20))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.CMBlunch0 = QtGui.QComboBox(self.frame)
        self.CMBlunch0.setGeometry(QtCore.QRect(200, 50, 151, 22))
        self.CMBlunch0.setObjectName(_fromUtf8("CMBlunch0"))
        self.CMBlunch0.addItem(_fromUtf8(""))
        self.CMBlunch0.addItem(_fromUtf8(""))
        self.CMBlunch0.addItem(_fromUtf8(""))
        self.CMBlunch0.addItem(_fromUtf8(""))
        self.CMBlunch0.addItem(_fromUtf8(""))
        self.CMBlunch0.addItem(_fromUtf8(""))
        self.CMBlunch0.addItem(_fromUtf8(""))
        self.CMBlunch0.addItem(_fromUtf8(""))
        self.CMBlunch0.addItem(_fromUtf8(""))
        self.CMBdinner0 = QtGui.QComboBox(self.frame)
        self.CMBdinner0.setGeometry(QtCore.QRect(30, 50, 151, 22))
        self.CMBdinner0.setObjectName(_fromUtf8("CMBdinner0"))
        self.CMBdinner0.addItem(_fromUtf8(""))
        self.CMBdinner0.addItem(_fromUtf8(""))
        self.CMBdinner0.addItem(_fromUtf8(""))
        self.CMBdinner0.addItem(_fromUtf8(""))
        self.CMBdinner0.addItem(_fromUtf8(""))
        self.CMBdinner0.addItem(_fromUtf8(""))
        self.CMBdinner0.addItem(_fromUtf8(""))
        self.CMBdinner0.addItem(_fromUtf8(""))
        self.CMBdinner0.addItem(_fromUtf8(""))
        self.CMBbreak1 = QtGui.QComboBox(self.frame)
        self.CMBbreak1.setGeometry(QtCore.QRect(360, 90, 151, 22))
        self.CMBbreak1.setObjectName(_fromUtf8("CMBbreak1"))
        self.CMBbreak1.addItem(_fromUtf8(""))
        self.CMBbreak1.addItem(_fromUtf8(""))
        self.CMBbreak1.addItem(_fromUtf8(""))
        self.CMBbreak1.addItem(_fromUtf8(""))
        self.CMBbreak1.addItem(_fromUtf8(""))
        self.CMBbreak1.addItem(_fromUtf8(""))
        self.CMBbreak1.addItem(_fromUtf8(""))
        self.CMBbreak1.addItem(_fromUtf8(""))
        self.CMBbreak1.addItem(_fromUtf8(""))
        self.CMBlunch1 = QtGui.QComboBox(self.frame)
        self.CMBlunch1.setGeometry(QtCore.QRect(200, 90, 151, 22))
        self.CMBlunch1.setObjectName(_fromUtf8("CMBlunch1"))
        self.CMBlunch1.addItem(_fromUtf8(""))
        self.CMBlunch1.addItem(_fromUtf8(""))
        self.CMBlunch1.addItem(_fromUtf8(""))
        self.CMBlunch1.addItem(_fromUtf8(""))
        self.CMBlunch1.addItem(_fromUtf8(""))
        self.CMBlunch1.addItem(_fromUtf8(""))
        self.CMBlunch1.addItem(_fromUtf8(""))
        self.CMBlunch1.addItem(_fromUtf8(""))
        self.CMBlunch1.addItem(_fromUtf8(""))
        self.CMBdinner1 = QtGui.QComboBox(self.frame)
        self.CMBdinner1.setGeometry(QtCore.QRect(30, 90, 151, 22))
        self.CMBdinner1.setObjectName(_fromUtf8("CMBdinner1"))
        self.CMBdinner1.addItem(_fromUtf8(""))
        self.CMBdinner1.addItem(_fromUtf8(""))
        self.CMBdinner1.addItem(_fromUtf8(""))
        self.CMBdinner1.addItem(_fromUtf8(""))
        self.CMBdinner1.addItem(_fromUtf8(""))
        self.CMBdinner1.addItem(_fromUtf8(""))
        self.CMBdinner1.addItem(_fromUtf8(""))
        self.CMBdinner1.addItem(_fromUtf8(""))
        self.CMBdinner1.addItem(_fromUtf8(""))
        self.CMBbreak2 = QtGui.QComboBox(self.frame)
        self.CMBbreak2.setGeometry(QtCore.QRect(360, 130, 151, 22))
        self.CMBbreak2.setObjectName(_fromUtf8("CMBbreak2"))
        self.CMBbreak2.addItem(_fromUtf8(""))
        self.CMBbreak2.addItem(_fromUtf8(""))
        self.CMBbreak2.addItem(_fromUtf8(""))
        self.CMBbreak2.addItem(_fromUtf8(""))
        self.CMBbreak2.addItem(_fromUtf8(""))
        self.CMBbreak2.addItem(_fromUtf8(""))
        self.CMBbreak2.addItem(_fromUtf8(""))
        self.CMBbreak2.addItem(_fromUtf8(""))
        self.CMBbreak2.addItem(_fromUtf8(""))
        self.CMBdinner2 = QtGui.QComboBox(self.frame)
        self.CMBdinner2.setGeometry(QtCore.QRect(30, 130, 151, 22))
        self.CMBdinner2.setObjectName(_fromUtf8("CMBdinner2"))
        self.CMBdinner2.addItem(_fromUtf8(""))
        self.CMBdinner2.addItem(_fromUtf8(""))
        self.CMBdinner2.addItem(_fromUtf8(""))
        self.CMBdinner2.addItem(_fromUtf8(""))
        self.CMBdinner2.addItem(_fromUtf8(""))
        self.CMBdinner2.addItem(_fromUtf8(""))
        self.CMBdinner2.addItem(_fromUtf8(""))
        self.CMBdinner2.addItem(_fromUtf8(""))
        self.CMBdinner2.addItem(_fromUtf8(""))
        self.CMBlunch2 = QtGui.QComboBox(self.frame)
        self.CMBlunch2.setGeometry(QtCore.QRect(200, 130, 151, 22))
        self.CMBlunch2.setObjectName(_fromUtf8("CMBlunch2"))
        self.CMBlunch2.addItem(_fromUtf8(""))
        self.CMBlunch2.addItem(_fromUtf8(""))
        self.CMBlunch2.addItem(_fromUtf8(""))
        self.CMBlunch2.addItem(_fromUtf8(""))
        self.CMBlunch2.addItem(_fromUtf8(""))
        self.CMBlunch2.addItem(_fromUtf8(""))
        self.CMBlunch2.addItem(_fromUtf8(""))
        self.CMBlunch2.addItem(_fromUtf8(""))
        self.CMBlunch2.addItem(_fromUtf8(""))
        self.CMBbreak3 = QtGui.QComboBox(self.frame)
        self.CMBbreak3.setGeometry(QtCore.QRect(360, 170, 151, 22))
        self.CMBbreak3.setObjectName(_fromUtf8("CMBbreak3"))
        self.CMBbreak3.addItem(_fromUtf8(""))
        self.CMBbreak3.addItem(_fromUtf8(""))
        self.CMBbreak3.addItem(_fromUtf8(""))
        self.CMBbreak3.addItem(_fromUtf8(""))
        self.CMBbreak3.addItem(_fromUtf8(""))
        self.CMBbreak3.addItem(_fromUtf8(""))
        self.CMBbreak3.addItem(_fromUtf8(""))
        self.CMBbreak3.addItem(_fromUtf8(""))
        self.CMBbreak3.addItem(_fromUtf8(""))
        self.CMBdinner3 = QtGui.QComboBox(self.frame)
        self.CMBdinner3.setGeometry(QtCore.QRect(30, 170, 151, 22))
        self.CMBdinner3.setObjectName(_fromUtf8("CMBdinner3"))
        self.CMBdinner3.addItem(_fromUtf8(""))
        self.CMBdinner3.addItem(_fromUtf8(""))
        self.CMBdinner3.addItem(_fromUtf8(""))
        self.CMBdinner3.addItem(_fromUtf8(""))
        self.CMBdinner3.addItem(_fromUtf8(""))
        self.CMBdinner3.addItem(_fromUtf8(""))
        self.CMBdinner3.addItem(_fromUtf8(""))
        self.CMBdinner3.addItem(_fromUtf8(""))
        self.CMBdinner3.addItem(_fromUtf8(""))
        self.CMBlunch3 = QtGui.QComboBox(self.frame)
        self.CMBlunch3.setGeometry(QtCore.QRect(200, 170, 151, 22))
        self.CMBlunch3.setObjectName(_fromUtf8("CMBlunch3"))
        self.CMBlunch3.addItem(_fromUtf8(""))
        self.CMBlunch3.addItem(_fromUtf8(""))
        self.CMBlunch3.addItem(_fromUtf8(""))
        self.CMBlunch3.addItem(_fromUtf8(""))
        self.CMBlunch3.addItem(_fromUtf8(""))
        self.CMBlunch3.addItem(_fromUtf8(""))
        self.CMBlunch3.addItem(_fromUtf8(""))
        self.CMBlunch3.addItem(_fromUtf8(""))
        self.CMBlunch3.addItem(_fromUtf8(""))
        self.CMBbreak4 = QtGui.QComboBox(self.frame)
        self.CMBbreak4.setGeometry(QtCore.QRect(360, 210, 151, 22))
        self.CMBbreak4.setObjectName(_fromUtf8("CMBbreak4"))
        self.CMBbreak4.addItem(_fromUtf8(""))
        self.CMBbreak4.addItem(_fromUtf8(""))
        self.CMBbreak4.addItem(_fromUtf8(""))
        self.CMBbreak4.addItem(_fromUtf8(""))
        self.CMBbreak4.addItem(_fromUtf8(""))
        self.CMBbreak4.addItem(_fromUtf8(""))
        self.CMBbreak4.addItem(_fromUtf8(""))
        self.CMBbreak4.addItem(_fromUtf8(""))
        self.CMBbreak4.addItem(_fromUtf8(""))
        self.CMBdinner4 = QtGui.QComboBox(self.frame)
        self.CMBdinner4.setGeometry(QtCore.QRect(30, 210, 151, 22))
        self.CMBdinner4.setObjectName(_fromUtf8("CMBdinner4"))
        self.CMBdinner4.addItem(_fromUtf8(""))
        self.CMBdinner4.addItem(_fromUtf8(""))
        self.CMBdinner4.addItem(_fromUtf8(""))
        self.CMBdinner4.addItem(_fromUtf8(""))
        self.CMBdinner4.addItem(_fromUtf8(""))
        self.CMBdinner4.addItem(_fromUtf8(""))
        self.CMBdinner4.addItem(_fromUtf8(""))
        self.CMBdinner4.addItem(_fromUtf8(""))
        self.CMBdinner4.addItem(_fromUtf8(""))
        self.CMBlunch4 = QtGui.QComboBox(self.frame)
        self.CMBlunch4.setGeometry(QtCore.QRect(200, 210, 151, 22))
        self.CMBlunch4.setObjectName(_fromUtf8("CMBlunch4"))
        self.CMBlunch4.addItem(_fromUtf8(""))
        self.CMBlunch4.addItem(_fromUtf8(""))
        self.CMBlunch4.addItem(_fromUtf8(""))
        self.CMBlunch4.addItem(_fromUtf8(""))
        self.CMBlunch4.addItem(_fromUtf8(""))
        self.CMBlunch4.addItem(_fromUtf8(""))
        self.CMBlunch4.addItem(_fromUtf8(""))
        self.CMBlunch4.addItem(_fromUtf8(""))
        self.CMBlunch4.addItem(_fromUtf8(""))
        self.CMBdinner5 = QtGui.QComboBox(self.frame)
        self.CMBdinner5.setGeometry(QtCore.QRect(30, 250, 151, 22))
        self.CMBdinner5.setObjectName(_fromUtf8("CMBdinner5"))
        self.CMBdinner5.addItem(_fromUtf8(""))
        self.CMBdinner5.addItem(_fromUtf8(""))
        self.CMBdinner5.addItem(_fromUtf8(""))
        self.CMBdinner5.addItem(_fromUtf8(""))
        self.CMBdinner5.addItem(_fromUtf8(""))
        self.CMBdinner5.addItem(_fromUtf8(""))
        self.CMBdinner5.addItem(_fromUtf8(""))
        self.CMBdinner5.addItem(_fromUtf8(""))
        self.CMBdinner5.addItem(_fromUtf8(""))
        self.CMBlunch5 = QtGui.QComboBox(self.frame)
        self.CMBlunch5.setGeometry(QtCore.QRect(200, 250, 151, 22))
        self.CMBlunch5.setObjectName(_fromUtf8("CMBlunch5"))
        self.CMBlunch5.addItem(_fromUtf8(""))
        self.CMBlunch5.addItem(_fromUtf8(""))
        self.CMBlunch5.addItem(_fromUtf8(""))
        self.CMBlunch5.addItem(_fromUtf8(""))
        self.CMBlunch5.addItem(_fromUtf8(""))
        self.CMBlunch5.addItem(_fromUtf8(""))
        self.CMBlunch5.addItem(_fromUtf8(""))
        self.CMBlunch5.addItem(_fromUtf8(""))
        self.CMBlunch5.addItem(_fromUtf8(""))
        self.CMBbreak5 = QtGui.QComboBox(self.frame)
        self.CMBbreak5.setGeometry(QtCore.QRect(360, 250, 151, 22))
        self.CMBbreak5.setObjectName(_fromUtf8("CMBbreak5"))
        self.CMBbreak5.addItem(_fromUtf8(""))
        self.CMBbreak5.addItem(_fromUtf8(""))
        self.CMBbreak5.addItem(_fromUtf8(""))
        self.CMBbreak5.addItem(_fromUtf8(""))
        self.CMBbreak5.addItem(_fromUtf8(""))
        self.CMBbreak5.addItem(_fromUtf8(""))
        self.CMBbreak5.addItem(_fromUtf8(""))
        self.CMBbreak5.addItem(_fromUtf8(""))
        self.CMBbreak5.addItem(_fromUtf8(""))
        self.CMBdinner6 = QtGui.QComboBox(self.frame)
        self.CMBdinner6.setGeometry(QtCore.QRect(30, 290, 151, 22))
        self.CMBdinner6.setObjectName(_fromUtf8("CMBdinner6"))
        self.CMBdinner6.addItem(_fromUtf8(""))
        self.CMBdinner6.addItem(_fromUtf8(""))
        self.CMBdinner6.addItem(_fromUtf8(""))
        self.CMBdinner6.addItem(_fromUtf8(""))
        self.CMBdinner6.addItem(_fromUtf8(""))
        self.CMBdinner6.addItem(_fromUtf8(""))
        self.CMBdinner6.addItem(_fromUtf8(""))
        self.CMBdinner6.addItem(_fromUtf8(""))
        self.CMBdinner6.addItem(_fromUtf8(""))
        self.CMBlunch6 = QtGui.QComboBox(self.frame)
        self.CMBlunch6.setGeometry(QtCore.QRect(200, 290, 151, 22))
        self.CMBlunch6.setObjectName(_fromUtf8("CMBlunch6"))
        self.CMBlunch6.addItem(_fromUtf8(""))
        self.CMBlunch6.addItem(_fromUtf8(""))
        self.CMBlunch6.addItem(_fromUtf8(""))
        self.CMBlunch6.addItem(_fromUtf8(""))
        self.CMBlunch6.addItem(_fromUtf8(""))
        self.CMBlunch6.addItem(_fromUtf8(""))
        self.CMBlunch6.addItem(_fromUtf8(""))
        self.CMBlunch6.addItem(_fromUtf8(""))
        self.CMBlunch6.addItem(_fromUtf8(""))
        self.CMBbreak6 = QtGui.QComboBox(self.frame)
        self.CMBbreak6.setGeometry(QtCore.QRect(360, 290, 151, 22))
        self.CMBbreak6.setObjectName(_fromUtf8("CMBbreak6"))
        self.CMBbreak6.addItem(_fromUtf8(""))
        self.CMBbreak6.addItem(_fromUtf8(""))
        self.CMBbreak6.addItem(_fromUtf8(""))
        self.CMBbreak6.addItem(_fromUtf8(""))
        self.CMBbreak6.addItem(_fromUtf8(""))
        self.CMBbreak6.addItem(_fromUtf8(""))
        self.CMBbreak6.addItem(_fromUtf8(""))
        self.CMBbreak6.addItem(_fromUtf8(""))
        self.CMBbreak6.addItem(_fromUtf8(""))
        self.TABnewList.addTab(self.restaurant, _fromUtf8(""))
        self.breakfast = QtGui.QWidget()
        self.breakfast.setObjectName(_fromUtf8("breakfast"))
        self.BTNmvRBreak = QtGui.QPushButton(self.breakfast)
        self.BTNmvRBreak.setGeometry(QtCore.QRect(280, 163, 20, 20))
        self.BTNmvRBreak.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/Button-Next.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.BTNmvRBreak.setIcon(icon)
        self.BTNmvRBreak.setFlat(True)
        self.BTNmvRBreak.setObjectName(_fromUtf8("BTNmvRBreak"))
        self.LSTWGselectedBreak = QtGui.QListWidget(self.breakfast)
        self.LSTWGselectedBreak.setGeometry(QtCore.QRect(310, 40, 256, 281))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("B Koodak"))
        self.LSTWGselectedBreak.setFont(font)
        self.LSTWGselectedBreak.setObjectName(_fromUtf8("LSTWGselectedBreak"))
        self.BTNmvLBreak = QtGui.QPushButton(self.breakfast)
        self.BTNmvLBreak.setGeometry(QtCore.QRect(280, 190, 20, 16))
        self.BTNmvLBreak.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/Button-Previous.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.BTNmvLBreak.setIcon(icon1)
        self.BTNmvLBreak.setFlat(True)
        self.BTNmvLBreak.setObjectName(_fromUtf8("BTNmvLBreak"))
        self.BTNmvUBreak = QtGui.QPushButton(self.breakfast)
        self.BTNmvUBreak.setGeometry(QtCore.QRect(570, 270, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.BTNmvUBreak.setFont(font)
        self.BTNmvUBreak.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/Button-Upload.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.BTNmvUBreak.setIcon(icon2)
        self.BTNmvUBreak.setFlat(True)
        self.BTNmvUBreak.setObjectName(_fromUtf8("BTNmvUBreak"))
        self.BTNmvDBreak = QtGui.QPushButton(self.breakfast)
        self.BTNmvDBreak.setGeometry(QtCore.QRect(570, 290, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.BTNmvDBreak.setFont(font)
        self.BTNmvDBreak.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/Button-Download.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.BTNmvDBreak.setIcon(icon3)
        self.BTNmvDBreak.setFlat(True)
        self.BTNmvDBreak.setObjectName(_fromUtf8("BTNmvDBreak"))
        self.LSTWGallBreak = QtGui.QListWidget(self.breakfast)
        self.LSTWGallBreak.setGeometry(QtCore.QRect(20, 40, 256, 281))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("B Koodak"))
        self.LSTWGallBreak.setFont(font)
        self.LSTWGallBreak.setObjectName(_fromUtf8("LSTWGallBreak"))
        self.label_15 = QtGui.QLabel(self.breakfast)
        self.label_15.setGeometry(QtCore.QRect(60, 10, 151, 21))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.breakfast)
        self.label_16.setGeometry(QtCore.QRect(360, 10, 151, 21))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.TABnewList.addTab(self.breakfast, _fromUtf8(""))
        self.breakfast1 = QtGui.QWidget()
        self.breakfast1.setObjectName(_fromUtf8("breakfast1"))
        self.LSTWGselectedLunch = QtGui.QListWidget(self.breakfast1)
        self.LSTWGselectedLunch.setGeometry(QtCore.QRect(310, 40, 256, 281))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("B Koodak"))
        self.LSTWGselectedLunch.setFont(font)
        self.LSTWGselectedLunch.setObjectName(_fromUtf8("LSTWGselectedLunch"))
        self.LSTWGallLunch = QtGui.QListWidget(self.breakfast1)
        self.LSTWGallLunch.setGeometry(QtCore.QRect(20, 40, 256, 281))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("B Koodak"))
        font.setBold(True)
        font.setWeight(75)
        self.LSTWGallLunch.setFont(font)
        self.LSTWGallLunch.setObjectName(_fromUtf8("LSTWGallLunch"))
        self.BTNmvLLunch = QtGui.QPushButton(self.breakfast1)
        self.BTNmvLLunch.setGeometry(QtCore.QRect(280, 190, 20, 16))
        self.BTNmvLLunch.setText(_fromUtf8(""))
        self.BTNmvLLunch.setIcon(icon1)
        self.BTNmvLLunch.setFlat(True)
        self.BTNmvLLunch.setObjectName(_fromUtf8("BTNmvLLunch"))
        self.BTNmvRLunch = QtGui.QPushButton(self.breakfast1)
        self.BTNmvRLunch.setGeometry(QtCore.QRect(280, 163, 20, 20))
        self.BTNmvRLunch.setText(_fromUtf8(""))
        self.BTNmvRLunch.setIcon(icon)
        self.BTNmvRLunch.setFlat(True)
        self.BTNmvRLunch.setObjectName(_fromUtf8("BTNmvRLunch"))
        self.BTNmvDLunch = QtGui.QPushButton(self.breakfast1)
        self.BTNmvDLunch.setGeometry(QtCore.QRect(570, 290, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.BTNmvDLunch.setFont(font)
        self.BTNmvDLunch.setText(_fromUtf8(""))
        self.BTNmvDLunch.setIcon(icon3)
        self.BTNmvDLunch.setFlat(True)
        self.BTNmvDLunch.setObjectName(_fromUtf8("BTNmvDLunch"))
        self.BTNmvULunch = QtGui.QPushButton(self.breakfast1)
        self.BTNmvULunch.setGeometry(QtCore.QRect(570, 270, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.BTNmvULunch.setFont(font)
        self.BTNmvULunch.setText(_fromUtf8(""))
        self.BTNmvULunch.setIcon(icon2)
        self.BTNmvULunch.setFlat(True)
        self.BTNmvULunch.setObjectName(_fromUtf8("BTNmvULunch"))
        self.label_17 = QtGui.QLabel(self.breakfast1)
        self.label_17.setGeometry(QtCore.QRect(60, 10, 151, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.breakfast1)
        self.label_18.setGeometry(QtCore.QRect(360, 10, 151, 21))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.TABnewList.addTab(self.breakfast1, _fromUtf8(""))
        self.lunch = QtGui.QWidget()
        self.lunch.setObjectName(_fromUtf8("lunch"))
        self.LSTWGselectedDinner = QtGui.QListWidget(self.lunch)
        self.LSTWGselectedDinner.setGeometry(QtCore.QRect(310, 40, 256, 281))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("B Koodak"))
        self.LSTWGselectedDinner.setFont(font)
        self.LSTWGselectedDinner.setObjectName(_fromUtf8("LSTWGselectedDinner"))
        item = QtGui.QListWidgetItem()
        self.LSTWGselectedDinner.addItem(item)
        self.LSTWGallDinner = QtGui.QListWidget(self.lunch)
        self.LSTWGallDinner.setGeometry(QtCore.QRect(20, 40, 256, 281))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("B Koodak"))
        font.setPointSize(9)
        self.LSTWGallDinner.setFont(font)
        self.LSTWGallDinner.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.LSTWGallDinner.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        # self.LSTWGallDinner.setSizeAdjustPolicy(QtGui.QAbstractScrollArea.AdjustIgnored)
        self.LSTWGallDinner.setAutoScrollMargin(14)
        self.LSTWGallDinner.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.LSTWGallDinner.setTextElideMode(QtCore.Qt.ElideLeft)
        self.LSTWGallDinner.setObjectName(_fromUtf8("LSTWGallDinner"))
        self.BTNmvLDinner = QtGui.QPushButton(self.lunch)
        self.BTNmvLDinner.setGeometry(QtCore.QRect(280, 190, 20, 16))
        self.BTNmvLDinner.setText(_fromUtf8(""))
        self.BTNmvLDinner.setIcon(icon1)
        self.BTNmvLDinner.setFlat(True)
        self.BTNmvLDinner.setObjectName(_fromUtf8("BTNmvLDinner"))
        self.BTNmvRDinner = QtGui.QPushButton(self.lunch)
        self.BTNmvRDinner.setGeometry(QtCore.QRect(280, 163, 20, 20))
        self.BTNmvRDinner.setText(_fromUtf8(""))
        self.BTNmvRDinner.setIcon(icon)
        self.BTNmvRDinner.setFlat(True)
        self.BTNmvRDinner.setObjectName(_fromUtf8("BTNmvRDinner"))
        self.BTNmvDDinner = QtGui.QPushButton(self.lunch)
        self.BTNmvDDinner.setGeometry(QtCore.QRect(570, 290, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.BTNmvDDinner.setFont(font)
        self.BTNmvDDinner.setText(_fromUtf8(""))
        self.BTNmvDDinner.setIcon(icon3)
        self.BTNmvDDinner.setFlat(True)
        self.BTNmvDDinner.setObjectName(_fromUtf8("BTNmvDDinner"))
        self.BTNmvUDinner = QtGui.QPushButton(self.lunch)
        self.BTNmvUDinner.setGeometry(QtCore.QRect(570, 270, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.BTNmvUDinner.setFont(font)
        self.BTNmvUDinner.setText(_fromUtf8(""))
        self.BTNmvUDinner.setIcon(icon2)
        self.BTNmvUDinner.setFlat(True)
        self.BTNmvUDinner.setObjectName(_fromUtf8("BTNmvUDinner"))
        self.label_19 = QtGui.QLabel(self.lunch)
        self.label_19.setGeometry(QtCore.QRect(360, 10, 151, 21))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.lunch)
        self.label_20.setGeometry(QtCore.QRect(60, 10, 151, 21))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.TABnewList.addTab(self.lunch, _fromUtf8(""))
        self.BTNsaveList = QtGui.QPushButton(self.createNewList)
        self.BTNsaveList.setEnabled(True)
        self.BTNsaveList.setGeometry(QtCore.QRect(70, 10, 75, 23))
        self.BTNsaveList.setAutoDefault(False)
        self.BTNsaveList.setDefault(False)
        self.BTNsaveList.setObjectName(_fromUtf8("BTNsaveList"))
        self.label_4 = QtGui.QLabel(self.createNewList)
        self.label_4.setGeometry(QtCore.QRect(280, 10, 51, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.LNEDTlistName = QtGui.QLineEdit(self.createNewList)
        self.LNEDTlistName.setEnabled(True)
        self.LNEDTlistName.setGeometry(QtCore.QRect(160, 10, 113, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setBold(True)
        font.setWeight(75)
        self.LNEDTlistName.setFont(font)
        self.LNEDTlistName.setObjectName(_fromUtf8("LNEDTlistName"))
        self.CMBXeditLists = QtGui.QComboBox(self.createNewList)
        self.CMBXeditLists.setGeometry(QtCore.QRect(430, 10, 121, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.CMBXeditLists.setFont(font)
        self.CMBXeditLists.setObjectName(_fromUtf8("CMBXeditLists"))
        self.label_21 = QtGui.QLabel(self.createNewList)
        self.label_21.setGeometry(QtCore.QRect(550, 10, 130, 20))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.BTNrmvlst = QtGui.QPushButton(self.createNewList)
        self.BTNrmvlst.setGeometry(QtCore.QRect(340, 10, 75, 23))
        self.BTNrmvlst.setObjectName(_fromUtf8("BTNrmvlst"))
        self.tabWidget.addTab(self.createNewList, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_23 = QtGui.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(260, 50, 201, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("B Koodak"))
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.BTNupdate = QtGui.QPushButton(self.tab_3)
        self.BTNupdate.setGeometry(QtCore.QRect(500, 50, 130, 30))
        self.BTNupdate.setObjectName(_fromUtf8("BTNupdate"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_29 = QtGui.QLabel(self.tab)
        self.label_29.setGeometry(QtCore.QRect(40, 22, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.tab)
        self.label_30.setGeometry(QtCore.QRect(40, 45, 261, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.label.setBuddy(self.LNEDTusername)
        self.label_2.setBuddy(self.LNEDTpassword)
        self.label_3.setBuddy(self.CMBXlists)
        self.label_23.setBuddy(self.LNEDTpassword)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.TABnewList.setCurrentIndex(3)
        QtCore.QObject.connect(self.CMBXeditLists, QtCore.SIGNAL(_fromUtf8("activated(QString)")), self.LNEDTlistName.setText)
        QtCore.QObject.connect(self.LNEDTlistName, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BTNsaveList.animateClick)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.LNEDTusername, self.LNEDTpassword)
        MainWindow.setTabOrder(self.LNEDTpassword, self.CMBXlists)
        MainWindow.setTabOrder(self.CMBXlists, self.BTNreserv)
        MainWindow.setTabOrder(self.BTNreserv, self.TABnewList)
        MainWindow.setTabOrder(self.TABnewList, self.CMBbreak0)
        MainWindow.setTabOrder(self.CMBbreak0, self.CMBlunch0)
        MainWindow.setTabOrder(self.CMBlunch0, self.CMBdinner0)
        MainWindow.setTabOrder(self.CMBdinner0, self.CMBbreak1)
        MainWindow.setTabOrder(self.CMBbreak1, self.CMBlunch1)
        MainWindow.setTabOrder(self.CMBlunch1, self.CMBdinner1)
        MainWindow.setTabOrder(self.CMBdinner1, self.CMBbreak2)
        MainWindow.setTabOrder(self.CMBbreak2, self.CMBlunch2)
        MainWindow.setTabOrder(self.CMBlunch2, self.CMBdinner2)
        MainWindow.setTabOrder(self.CMBdinner2, self.CMBbreak3)
        MainWindow.setTabOrder(self.CMBbreak3, self.CMBlunch3)
        MainWindow.setTabOrder(self.CMBlunch3, self.CMBdinner3)
        MainWindow.setTabOrder(self.CMBdinner3, self.CMBbreak4)
        MainWindow.setTabOrder(self.CMBbreak4, self.CMBlunch4)
        MainWindow.setTabOrder(self.CMBlunch4, self.CMBdinner4)
        MainWindow.setTabOrder(self.CMBdinner4, self.CMBbreak5)
        MainWindow.setTabOrder(self.CMBbreak5, self.CMBlunch5)
        MainWindow.setTabOrder(self.CMBlunch5, self.CMBdinner5)
        MainWindow.setTabOrder(self.CMBdinner5, self.CMBbreak6)
        MainWindow.setTabOrder(self.CMBbreak6, self.CMBlunch6)
        MainWindow.setTabOrder(self.CMBlunch6, self.CMBdinner6)
        MainWindow.setTabOrder(self.CMBdinner6, self.LSTWGallBreak)
        MainWindow.setTabOrder(self.LSTWGallBreak, self.LSTWGselectedBreak)
        MainWindow.setTabOrder(self.LSTWGselectedBreak, self.BTNmvRBreak)
        MainWindow.setTabOrder(self.BTNmvRBreak, self.BTNmvLBreak)
        MainWindow.setTabOrder(self.BTNmvLBreak, self.BTNmvUBreak)
        MainWindow.setTabOrder(self.BTNmvUBreak, self.BTNmvDBreak)
        MainWindow.setTabOrder(self.BTNmvDBreak, self.LSTWGallLunch)
        MainWindow.setTabOrder(self.LSTWGallLunch, self.LSTWGselectedLunch)
        MainWindow.setTabOrder(self.LSTWGselectedLunch, self.BTNmvRLunch)
        MainWindow.setTabOrder(self.BTNmvRLunch, self.BTNmvLLunch)
        MainWindow.setTabOrder(self.BTNmvLLunch, self.BTNmvULunch)
        MainWindow.setTabOrder(self.BTNmvULunch, self.BTNmvDLunch)
        MainWindow.setTabOrder(self.BTNmvDLunch, self.LSTWGallDinner)
        MainWindow.setTabOrder(self.LSTWGallDinner, self.LSTWGselectedDinner)
        MainWindow.setTabOrder(self.LSTWGselectedDinner, self.BTNmvRDinner)
        MainWindow.setTabOrder(self.BTNmvRDinner, self.BTNmvLDinner)
        MainWindow.setTabOrder(self.BTNmvLDinner, self.BTNmvUDinner)
        MainWindow.setTabOrder(self.BTNmvUDinner, self.BTNmvDDinner)
        MainWindow.setTabOrder(self.BTNmvDDinner, self.tabWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "رزور خودکار غذا (نسخه بتا 0.9.1.0)", None))
        self.label.setText(_translate("MainWindow", "نام کاربری", None))
        self.label_2.setText(_translate("MainWindow", "پسورد", None))
        self.label_3.setText(_translate("MainWindow", "انتخاب لیست", None))
        self.LNEDTusername.setPlaceholderText(_translate("MainWindow", "username", None))
        self.LNEDTpassword.setPlaceholderText(_translate("MainWindow", "password", None))
        self.BTNreserv.setText(_translate("MainWindow", "رزرو", None))
        self.CHKBXthis.setText(_translate("MainWindow", "هفته ی جاری", None))
        self.CHKBXnext.setText(_translate("MainWindow", "هفته ی آینده", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mainPage), _translate("MainWindow", "صفحه اصلی", None))
        self.label_5.setText(_translate("MainWindow", " شنبه", None))
        self.CMBbreak0.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBbreak0.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBbreak0.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBbreak0.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBbreak0.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBbreak0.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBbreak0.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBbreak0.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBbreak0.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.label_6.setText(_translate("MainWindow", "1 شنبه", None))
        self.label_7.setText(_translate("MainWindow", "صبحانه", None))
        self.label_8.setText(_translate("MainWindow", "ناهار", None))
        self.label_9.setText(_translate("MainWindow", "شام", None))
        self.label_10.setText(_translate("MainWindow", "2 شنبه", None))
        self.label_11.setText(_translate("MainWindow", "3 شنبه", None))
        self.label_12.setText(_translate("MainWindow", "4 شنبه", None))
        self.label_13.setText(_translate("MainWindow", "5 شنبه", None))
        self.label_14.setText(_translate("MainWindow", " جمعه", None))
        self.CMBlunch0.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBlunch0.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBlunch0.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBlunch0.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBlunch0.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBlunch0.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBlunch0.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBlunch0.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBlunch0.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.CMBdinner0.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBdinner0.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBdinner0.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBdinner0.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBdinner0.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBdinner0.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBdinner0.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBdinner0.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBdinner0.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.CMBbreak1.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBbreak1.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBbreak1.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBbreak1.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBbreak1.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBbreak1.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBbreak1.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBbreak1.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBbreak1.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.CMBlunch1.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBlunch1.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBlunch1.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBlunch1.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBlunch1.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBlunch1.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBlunch1.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBlunch1.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBlunch1.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.CMBdinner1.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBdinner1.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBdinner1.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBdinner1.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBdinner1.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBdinner1.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBdinner1.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBdinner1.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBdinner1.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.CMBbreak2.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBbreak2.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBbreak2.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBbreak2.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBbreak2.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBbreak2.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBbreak2.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBbreak2.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBbreak2.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.CMBdinner2.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBdinner2.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBdinner2.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBdinner2.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBdinner2.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBdinner2.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBdinner2.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBdinner2.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBdinner2.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.CMBlunch2.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBlunch2.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBlunch2.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBlunch2.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBlunch2.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBlunch2.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBlunch2.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBlunch2.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBlunch2.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.CMBbreak3.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBbreak3.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBbreak3.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBbreak3.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBbreak3.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBbreak3.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBbreak3.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBbreak3.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBbreak3.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.CMBdinner3.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBdinner3.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBdinner3.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBdinner3.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBdinner3.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBdinner3.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBdinner3.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBdinner3.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBdinner3.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.CMBlunch3.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBlunch3.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBlunch3.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBlunch3.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBlunch3.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBlunch3.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBlunch3.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBlunch3.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBlunch3.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.CMBbreak4.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBbreak4.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBbreak4.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBbreak4.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBbreak4.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBbreak4.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBbreak4.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBbreak4.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBbreak4.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.CMBdinner4.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBdinner4.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBdinner4.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBdinner4.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBdinner4.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBdinner4.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBdinner4.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBdinner4.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBdinner4.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.CMBlunch4.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBlunch4.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBlunch4.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBlunch4.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBlunch4.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBlunch4.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBlunch4.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBlunch4.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBlunch4.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.CMBdinner5.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBdinner5.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBdinner5.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBdinner5.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBdinner5.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBdinner5.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBdinner5.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBdinner5.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBdinner5.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.CMBlunch5.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBlunch5.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBlunch5.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBlunch5.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBlunch5.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBlunch5.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBlunch5.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBlunch5.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBlunch5.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.CMBbreak5.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBbreak5.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBbreak5.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBbreak5.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBbreak5.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBbreak5.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBbreak5.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBbreak5.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBbreak5.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.CMBdinner6.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBdinner6.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBdinner6.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBdinner6.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBdinner6.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBdinner6.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBdinner6.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBdinner6.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBdinner6.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.CMBlunch6.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBlunch6.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBlunch6.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBlunch6.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBlunch6.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBlunch6.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBlunch6.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBlunch6.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBlunch6.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.CMBbreak6.setItemText(0, _translate("MainWindow", "ارم", None))
        self.CMBbreak6.setItemText(1, _translate("MainWindow", "دانشکده ی هنر و معماری", None))
        self.CMBbreak6.setItemText(2, _translate("MainWindow", "خوابگاه شهید دستغیب", None))
        self.CMBbreak6.setItemText(3, _translate("MainWindow", "دانشکده ی علوم", None))
        self.CMBbreak6.setItemText(4, _translate("MainWindow", "دانشکده ی مهندسی نفت و گاز", None))
        self.CMBbreak6.setItemText(5, _translate("MainWindow", "مرکزی", None))
        self.CMBbreak6.setItemText(6, _translate("MainWindow", "دانشکده ی کشاورزی", None))
        self.CMBbreak6.setItemText(7, _translate("MainWindow", "دانشکده ی دامپزشکی", None))
        self.CMBbreak6.setItemText(8, _translate("MainWindow", "خوابگاه دامپزشکی", None))
        self.TABnewList.setTabText(self.TABnewList.indexOf(self.restaurant), _translate("MainWindow", " رستوران  ", None))
        self.label_15.setText(_translate("MainWindow", "لیست  غذا ها ی صبحانه", None))
        self.label_16.setText(_translate("MainWindow", "لیست انتخاب های شما", None))
        self.TABnewList.setTabText(self.TABnewList.indexOf(self.breakfast), _translate("MainWindow", "صبحانه", None))
        self.label_17.setText(_translate("MainWindow", "لیست  غذا ها ی ناهار", None))
        self.label_18.setText(_translate("MainWindow", "لیست انتخاب های شما", None))
        self.TABnewList.setTabText(self.TABnewList.indexOf(self.breakfast1), _translate("MainWindow", " ناهار", None))
        __sortingEnabled = self.LSTWGselectedDinner.isSortingEnabled()
        self.LSTWGselectedDinner.setSortingEnabled(False)
        self.LSTWGselectedDinner.setSortingEnabled(__sortingEnabled)
        self.label_19.setText(_translate("MainWindow", "لیست انتخاب های شما", None))
        self.label_20.setText(_translate("MainWindow", "لیست  غذا ها ی شام", None))
        self.TABnewList.setTabText(self.TABnewList.indexOf(self.lunch), _translate("MainWindow", "شام", None))
        self.BTNsaveList.setText(_translate("MainWindow", "ذخیره", None))
        self.label_4.setText(_translate("MainWindow", "نام لیست", None))
        self.label_21.setText(_translate("MainWindow", " لیست های ساخته شده", None))
        self.BTNrmvlst.setText(_translate("MainWindow", "حذف لیست", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.createNewList), _translate("MainWindow", "  ساخت و تغییر لیست", None))
        self.label_23.setText(_translate("MainWindow", "بروز رسانی لیست غذا ها و رستوران ها", None))
        self.BTNupdate.setText(_translate("MainWindow", "بروز رسانی ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "ابزار", None))
        self.label_29.setText(_translate("MainWindow", "version 0.9.1.0 (beta)", None))
        self.label_30.setText(_translate("MainWindow", "kazemihabib1996@gmail.com", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "درباره", None))

